#!/usr/bin/env bash
searchpath=$1
g=$2

fuzzer=""
if [[ $g == "-" ]]; then
    fuzzer="fzf"
else
    fuzzer="gfzf"
fi

chosen=$(fd . $searchpath --hidden | $fuzzer --scheme=path)
[[ $? != 0 ]] && exit 1

echo "$chosen" | xsel -ib