#!/usr/bin/env bash
# if [ -t 0 ]; then
#     exec fzf $@
# else
    fifoname=$(mktemp --dry-run -t prog_XXXXXX).fifo-$RANDOM-$$
    mkfifo -m 0600 "$fifoname"
    wezterm bash -c "fzf $@ < $fifoname" > $fifoname
    # wezterm --config-file ~/.wezterm.fzf.lua start --class Gfzf bash -c "fzf --color=bw --border $@ < $fifoname" > $fifoname
# fi