#!/usr/bin/env bash
cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/pathed"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
# `stest` is from dmenu
if stest -dqr -n "$cache" $PATH; then
    stest -flx $PATH | sort -u | tee "$cache"
else
    cat "$cache"
fi
