#!/usr/bin/env bash
declare -A actions
actions=( 
    ["test"]="notify-send \"TEST SYSACTION\""
    ["kill xinit"]="killall xinit"
    ["sleep"]="systemctl suspend"
    ["shutdown"]="shutdown -h now"
    ["reboot"]="reboot"
)

selected=$(printf "%s\n" "${!actions[@]}" | dmenu -l 5)

[[ $selected ]] || exit 1

eval "${actions[$selected]}"